export const gamesNearYouDummy: Array<Game> = [
	{
		sport: "Football",
		maxPlayers: 22,
		currPlayers: [
			{ id: 10, name: "Hannah Irving" },
			{ id: 11, name: "Ian Jackson" },
			{ id: 12, name: "Julia King" },
		],
		dateTime: "2024-05-16T18:00:00Z",
		duration: 90,
		name: "Sunday Morning Football",
		addr1: "123 Park Lane",
		addr2: "Suite 200",
		postcode: "12345",
		gameId: "game001",
	},
	{
		sport: "Basketball",
		maxPlayers: 10,
		currPlayers: [
			{ id: 14, name: "Laura Martin" },
			{ id: 15, name: "Michael Nelson" },
			{ id: 16, name: "Nina Owens" },
			{ id: 17, name: "Oscar Perez" },
			{ id: 18, name: "Paula Quinn" },
			{ id: 19, name: "Quentin Roberts" },
			{ id: 20, name: "Rachel Stevens" },
		],
		dateTime: "2024-05-17T11:15:00Z",
		duration: 60,
		name: "Afternoon Basketball",
		addr1: "456 Court St",
		addr2: "Apt 3B",
		postcode: "67890",
		gameId: "game002",
	},
	{
		sport: "Tennis",
		maxPlayers: 4,
		currPlayers: [{ id: 1, name: "John Smith" }],
		dateTime: "2024-05-18T20:00:00Z",
		duration: 120,
		name: "Morning Tennis Match",
		addr1: "789 Tennis Court",
		addr2: "Level 1",
		postcode: "11223",
		gameId: "game003",
	},
	{
		sport: "Football",
		maxPlayers: 22,
		currPlayers: [
			{ id: 6, name: "Diana Evans" },
			{ id: 7, name: "Ethan Foster" },
			{ id: 8, name: "Fiona Green" },
			{ id: 9, name: "George Harris" },
		],
		dateTime: "2024-05-22T19:45:00Z",
		duration: 90,
		name: "Evening Football Game",
		addr1: "101 Stadium Rd",
		addr2: "Field 2",
		postcode: "33445",
		gameId: "game004",
	},
	{
		sport: "Basketball",
		maxPlayers: 10,
		currPlayers: [
			{ id: 3, name: "Alice Johnson" },
			{ id: 4, name: "Bob Brown" },
			{ id: 5, name: "Charlie Davis" },
			{ id: 6, name: "Diana Evans" },
			{ id: 7, name: "Ethan Foster" },
			{ id: 8, name: "Fiona Green" },
			{ id: 9, name: "George Harris" },
			{ id: 10, name: "Hannah Irving" },
			{ id: 11, name: "Ian Jackson" },
			{ id: 12, name: "Julia King" },
		],
		dateTime: "2024-06-15T14:00:00Z",
		duration: 60,
		name: "Lunchtime Basketball",
		addr1: "202 Gymnasium Ave",
		addr2: "Court 1",
		postcode: "55667",
		gameId: "game005",
	},
];
