export const upcomingGamesDummy: Array<Game> = [
	{
		sport: "Football",
		maxPlayers: 22,
		currPlayers: [
			{ id: 1, name: "John Smith" },
			{ id: 2, name: "Jane Doe" },
			{ id: 3, name: "Alice Johnson" },
			{ id: 4, name: "Bob Brown" },
			{ id: 5, name: "Charlie Davis" },
		],
		dateTime: "2024-06-01T10:00:00Z",
		duration: 90,
		name: "Sunday League Football",
		addr1: "123 Main St",
		addr2: "Field 4",
		postcode: "12345",
		gameId: "game001",
	},
	{
		sport: "Basketball",
		maxPlayers: 10,
		currPlayers: [
			{ id: 6, name: "Diana Evans" },
			{ id: 7, name: "Ethan Foster" },
			{ id: 8, name: "Fiona Green" },
		],
		dateTime: "2024-06-02T14:00:00Z",
		duration: 48,
		name: "5v5 Hoops",
		addr1: "456 Elm St",
		addr2: "Gym Court 1",
		postcode: "67890",
		gameId: "game002",
	},
	{
		sport: "Tennis",
		maxPlayers: 4,
		currPlayers: [
			{ id: 9, name: "George Harris" },
			{ id: 10, name: "Hannah Irving" },
		],
		dateTime: "2024-06-03T09:00:00Z",
		duration: 60,
		name: "Causal Mixed Doubles",
		addr1: "789 Oak St",
		addr2: "Court 2",
		postcode: "11223",
		gameId: "game003",
	},
];
