export const Users: Array<User> = [
	{ id: 1, name: "John Smith" },
	{ id: 2, name: "Jane Doe" },
	{ id: 3, name: "Alice Johnson" },
	{ id: 4, name: "Bob Brown" },
	{ id: 5, name: "Charlie Davis" },
	{ id: 6, name: "Diana Evans" },
	{ id: 7, name: "Ethan Foster" },
	{ id: 8, name: "Fiona Green" },
	{ id: 9, name: "George Harris" },
	{ id: 10, name: "Hannah Irving" },
	{ id: 11, name: "Ian Jackson" },
	{ id: 12, name: "Julia King" },
	{ id: 13, name: "Kevin Lee" },
	{ id: 14, name: "Laura Martin" },
	{ id: 15, name: "Michael Nelson" },
	{ id: 16, name: "Nina Owens" },
	{ id: 17, name: "Oscar Perez" },
	{ id: 18, name: "Paula Quinn" },
	{ id: 19, name: "Quentin Roberts" },
	{ id: 20, name: "Rachel Stevens" },
];
